/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Speak {
  public static int setPitch(int value) {
    return SpeakJNI.setPitch(value);
  }

  public static int setAmplitude(int value) {
    return SpeakJNI.setAmplitude(value);
  }

  public static int setPitchRange(int value) {
    return SpeakJNI.setPitchRange(value);
  }

  public static int initialise() {
    return SpeakJNI.initialise();
  }

  public static int espeak(String arr) {
    return SpeakJNI.espeak(arr);
  }

  public static int cancel() {
    return SpeakJNI.cancel();
  }

  public static int isPlaying() {
    return SpeakJNI.isPlaying();
  }

  public static int terminate() {
    return SpeakJNI.terminate();
  }

}
